In [1]:
import numpy as np

In [2]:
a = np.array([20,18,37])

In [33]:
a

array([20, 18, 37])

In [4]:
np.array([(36.8,35.8,37),(36.2,35.9,36.1)], dtype=float)

array([[36.8, 35.8, 37. ],
       [36.2, 35.9, 36.1]])

In [5]:
np.array([(36.8,35.8,37),(36.2,35.9,36.1)])

array([[36.8, 35.8, 37. ],
       [36.2, 35.9, 36.1]])

In [40]:
b=np.array([(36.8,35.8,37),(36.2,35.9,36.1)])
b.shape #Get Shape

(2, 3)

In [9]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [10]:
np.arange(0, 15, 3)

array([ 0,  3,  6,  9, 12])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(0,6,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ,
       5.2, 5.4, 5.6, 5.8])

In [18]:
np.linspace(5,10,3)

array([ 5. ,  7.5, 10. ])

In [19]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [22]:
np.linspace(5,10, 3, endpoint=False)

array([5.        , 6.66666667, 8.33333333])

In [24]:
np.linspace(5,10, 3, endpoint=False, retstep=True)

(array([5.        , 6.66666667, 8.33333333]), 1.6666666666666667)

In [25]:
b = np.arange(0, 10, 3)
b

array([0, 3, 6, 9])

In [26]:
b.reshape(2,2)

array([[0, 3],
       [6, 9]])

In [28]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((3,5,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [30]:
np.zeros((3,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [41]:
c = np.array([1,2,3,4])
print(c)

[1 2 3 4]


In [42]:
c

array([1, 2, 3, 4])

In [43]:
c - 1

array([0, 1, 2, 3])

In [44]:
c * 2

array([2, 4, 6, 8])

In [45]:
c / 2

array([0.5, 1. , 1.5, 2. ])

In [46]:
d = np.array([3,2,3,2])
c + d

array([4, 4, 6, 6])

In [48]:
c ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [49]:
np.cos(c)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])